import type { Metadata } from "next";

import "./globals.css";

import { SessionProvider } from "next-auth/react";
import { Ubuntu } from "next/font/google";
const ubuntu = Ubuntu({
  weight: "300",
  style: "normal",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${ubuntu.className} antialiased`}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
